version: '2'

volumes:
  postgres-data:
    driver: local

services:
  db:
    container_name: issue_tracker_db
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    container_name: issue_tracker_api
    build: .
    command: bundle exec puma -b 'tcp://0.0.0.0:3000'
    volumes:
      - .:/usr/src/app

    ports:
      - 3000:3000
    depends_on:
      - db
