development: &development
  adapter: postgresql
  encoding: unicode
  database: issue_tracker_api_development
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>

test:
  <<: *development
  database: issue_tracker_api_test
