# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bcba4348fdab6f228b38fb6384ee708993b2660279d5721fd8979dd438bded409b556394a6267d75defcf734c3454a25df3c923eadde193e85daed8a23dd3d9

test:
  secret_key_base: 3099425a2bbe539eecb29e76a509430992711e1f80a15008ddc800997831dc4743277da5adddc0c25ff692c5790d5bc09aba10863bd46dc2c4cb61a22efec51b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
